### ISSUE TITLE
Attempting to load modules using a list of Paths always raises an error

### ISSUE THREAD

**Issue by parafoxia** [FasterSpeeding/Tanjun#55]
https://github.com/FasterSpeeding/Tanjun/blob/2de1d6b095ee4cd27b9473ac8873196f9824ca13/tanjun/clients.py#L1199-L1213

The problem seems to originate from this error always being raised if the argument type is not `str`, despite loading correctly (presumably, anyways).

**Comment by FasterSpeeding** [comment]
Looks like a small logic mistake, will fix
